data.fetcher.timeout=3000

#DataBase
spring.datasource.url=jdbc:postgresql://localhost:5432/recipe_db
spring.datasource.username=recipe_user
spring.datasource.password=n9fjGp6Xh9QpWGc36Xao
spring.datasource.driver-class-name=org.postgresql.Driver

#Flyaway
flyway.baselineOnMigrate=true