package com.recipe.dao.entities;// default package
// Generated Dec. 27, 2025, 11:42:01 a.m. by Hibernate Tools 7.2.0.Final


import jakarta.persistence.*;
import lombok.*;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * Ingredient generated by hbm2java
 */
@Entity
@Table(name="ingredient"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Ingredient{

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name="id", unique=true, nullable=false)
    private UUID id;

    @Column(name="name", unique=true, length=255)
    private String name;

    @OneToMany(fetch=FetchType.LAZY, mappedBy="ingredient")
    @Builder.Default
    private Set<RecipeIngredients> recipeIngredientses = new HashSet<RecipeIngredients>(0);

    public void addRecipeIngredients(RecipeIngredients recipeIngredients)
    {
        recipeIngredients.setIngredient(this);
        recipeIngredientses.add(recipeIngredients);
    }

}


