package com.recipe.dao.entities;// default package
// Generated Dec. 27, 2025, 11:42:01 a.m. by Hibernate Tools 7.2.0.Final



import jakarta.persistence.*;
import lombok.*;

import java.io.Serializable;
import java.util.UUID;

/**
 * RecipeIngredients generated by hbm2java
 */
@Entity
@Table(name="recipe_ingredients"
    ,schema="public"
)
@Builder
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class RecipeIngredients  implements Serializable {

    @Id
    @Column(name="id", unique=true, nullable=false)
    private UUID id;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="recipe_id", nullable=false)
     private Recipe recipe;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ingredient_id", nullable=false)
     private Ingredient ingredient;

    @Column(name="quantity", nullable=false, length=10)
    private String quantity;

    @Column(name="unit", nullable=false, length=10)
    private String unit;

    @Column(name="notes", length=255)
    private String notes;
}


